apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: ghcr.io/cs-muic/scalable-p1-stellardropthebeat/p1-backend
        env:
          - name: MARIADB_USER
            valueFrom:
              secretKeyRef:
                name: secret
                key: user
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: password
          - name: MARIADB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mariadb-config
                key: mariadb-url
      imagePullSecrets:
        - name: myregistrykey